[package]
name = "secret_handshake"
version = "0.2.2"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "Implementation of the secret-handshake protocol."
repository = "https://github.com/AljoschaMeyer/secret-handshake-rs"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
sodiumoxide = "0.0.15"
libc = "0.2"
futures = "0.1.14"
tokio-io = "0.1.2"
box_stream = "0.2.1"

[dev-dependencies]
partial-io = { version = "0.2.3", features = ["quickcheck", "tokio"] }
quickcheck = "0.4.1"

[build-dependencies]
gcc = "0.3"
